<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>net.mmo.utils.kism</groupId>
	<artifactId>kis-monitoring</artifactId>
	<name>KIS-Monitoring</name>
	<version>1.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<description>Keep-it-simple Monitoring</description>
	<!-- url>tbd</url -->
	<inceptionYear>2021</inceptionYear>
	<developers>
		<developer>
			<roles>
				<role>All-in-one</role>
			</roles>
			<id>mmo</id>
			<name>Michael Moser</name>
			<email>17732576+mmoser18@users.noreply.github.com</email>
			<timezone>"Europe/Zurich" (UTC+01:00)</timezone>
		</developer>
	</developers>

	<!-- to be finalized if/when I move this to GitHub / MMO
	<issueManagement>
		<system>github</system>
		<url>http://github.com/tbd/issues</url>
	</issueManagement>

	<scm>
		<connection>scm:git:git://github.com/mmoser18/kismon.git</connection>
		<developerConnection>scm:git:git@github.com:mmoser18/kismon.git</developerConnection>
		<url>http://github.com/mmoser18/kismon</url>
	</scm>
	 -->

	<properties>
		<java.version>25</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<!-- some local settings: -->
		<user.home>${env.USERPROFILE}</user.home>
		<user.repo>${user.home}/.m2/m2repository/</user.repo>
		<!-- worked with Vaadin: 18.0.4 and then again with 22.0.1, 22.0.2, 23.0.1, 23.0.2, 
		     but did NOT work with v19.0.x..v21.0.4: -->
		<!-- last version that does NOT validate the Chart license during build time ->
		<vaadin.version>23.1.7</vaadin.version> 
		<!- -->
		<!-- newest version / but since v23.2.0 this refuses to build without license ||-( : -->
		<!-- vaadin.version>24.3.8</vaadin.version -->
		<vaadin.version>25.1.1</vaadin.version>
		<!-- -->
		<wdm.version>6.3.3</wdm.version>	<!-- wdm = WebDriver Manager -->
		<!-- should be passed in via an environment variable or some -D option -->
		<webdriver.maven.repo>${user.repo}</webdriver.maven.repo>
		
		<h2.version>2.4.240</h2.version>
		<archunit-junit5.version>1.4.1</archunit-junit5.version>
		
		<sshj.version>0.40.0</sshj.version>
		<mail.version>1.4.7</mail.version>
		<jaxb.version>4.0.7</jaxb.version> <!-- https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl -->
	</properties>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.5</version> <!-- for some stupid reason one can not use a placeholder for this version number ||-( -->
		<!-- <relativePath/> lookup parent from repository -->
	</parent>

	<repositories>
		<!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->
		<repository>
			<id>central</id> <!-- Main Maven repository -->
			<url>https://repo.maven.apache.org/maven2</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<!-- Repository used by many Vaadin add-ons: -->
		<repository>
			<id>Vaadin Directory</id>
			<url>https://maven.vaadin.com/vaadin-addons</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<!-- Main Maven repository -->
		<pluginRepository>
			<id>central</id>
			<url>https://repo.maven.apache.org/maven2</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- Vaadin stuff: -->
		<dependency>
			<groupId>com.vaadin</groupId>
			<!-- Replace artifactId with vaadin-core to use only free components -->
			<artifactId>vaadin</artifactId>
			<!-- Webjars are only needed when running in Vaadin 13 compatibility mode ->
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.webjar</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.webjars.bowergithub.insites</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.webjars.bowergithub.polymer</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.webjars.bowergithub.polymerelements</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.webjars.bowergithub.vaadin</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.webjars.bowergithub.webcomponents</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
			<!- -->
		</dependency>

		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
			<!-- Excluding so that webjars are not included. / is this still required? ->
			<exclusions>
				<exclusion>
					<groupId>com.vaadin</groupId>
					<artifactId>vaadin-core</artifactId>
				</exclusion>
			</exclusions>
			<!- -->
		</dependency>

		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-dev</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<!-- to enable live reload in the application (see https://vaadin.com/docs/latest/configuration/live-reload/spring-boot): -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- enable Spring Security: -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		<!-- ->
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-testbench</artifactId>
			<scope>test</scope>
		</dependency>
		<!- -->
		<!-- SpringBoot security (for login screen) -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
		</dependency>
		<!-- Spring Security references HttpServletRequest and -Response. 
			When building for a barebones servlet container (Tomcat, Jetty, etc) 
			instead of a full fledged Java EE application server (WildFly, TomEE, GlassFish, 
			Liberty, etc), one thus needs to add the javax.servlet API to the compile time 
			dependencies. It's not needed to include it in the build, it's already provided 
			by the target servlet container:
		->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>
		<!- If you happen to actually deploy to a Java EE 7+ application server 
			like WildFly, use the below dependency instead. It covers the entire Java 
			EE API, including javax.servlet 
		->
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>7.0</version>
			<scope>provided</scope>
		</dependency>
		<!- -->

		<!-- logback classic has a transitive reference to slf4j - so no explicit slf4j dependency should be required, but... -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
		</dependency>
		<!-- -->

		<dependency>
			<groupId>com.hierynomus</groupId>
			<artifactId>sshj</artifactId>
			<version>${sshj.version}</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/javax.mail/mail -->
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>${mail.version}</version>
		</dependency>

		<!-- jackson-core ->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<!- -->

		<!-- JUnit 5 = JUnit Platform + JUnit Jupiter + JUnit Vintage -->
		<!-- required for IT tests with SpringBoot: -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!--database dependencies - this is also required to enable auto-configuration for the h2 database -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<!-- Using in-memory database H2 -->
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<!--  -->
		<!-- Using PostGres DB / not tested ->
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<!-   -->
		<!-- Using MySQL DB / not tested ->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<!-  -->
		<!-- https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8 -->
		<dependency>
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc8</artifactId>
			<version>23.26.1.0.0</version><!--$NO-MVN-MAN-VER$-->
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client -->
		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
			<version>3.5.8</version><!--$NO-MVN-MAN-VER$-->
		</dependency>

		<!-- required when using Vaadin BeanValidators: -->
		<!-- Hibernate validator - Bean validation API Implementation -->
		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>9.1.0.Final</version><!--$NO-MVN-MAN-VER$-->
		</dependency>

		<!-- the following are obviously referenced by hibernate validator - why are these not in its pom? -->
		<dependency>
			<groupId>javax.el</groupId>
			<artifactId>javax.el-api</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.web</groupId>
			<artifactId>javax.el</artifactId>
			<version>2.2.6</version>
		</dependency>

		<!-- webdriver-manager to allow running the Integration Tests on Chrome
			This is used from the JUnit test class and downloads the correct version 
			of the Chrome web driver, if it is missing. 
			The webdriver itself is then used by the integration tests. 
		->
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>${wdm.version}</version>
			<scope>test</scope>
		</dependency>
		-->
		
		<!-- Lombok - generates setters and getters and allows for other goodies like @Slf4j, toString(), etc. -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<!-- fitting version is already defined in spring-boot-dependencies -->
			<type>jar</type>
			<scope>provided</scope>
		</dependency>


		<!-- for AspectJ: -->
		<!-- Instrumentations are enabled as a javaagent that run on the JVM. 
			Springs org.springframework:spring-instrument.jar ships the InstrumentationSavingAgent which 
			saves the instrumentation.
			To run AspectJ load-time weaving in a spring environment it is necessary to have these two instrumentations: 
		-->
		<!-- AspectJ version is mentioned in springboot-starter ->
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjtools</artifactId> 
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-instrument</artifactId>
		</dependency>
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
		</dependency>
		<!- -->

		<!-- for ArchUnit-tests (executed during UTs): -->
		<dependency>
			<groupId>com.tngtech.archunit</groupId>
			<artifactId>archunit-junit5</artifactId>
			<version>${archunit-junit5.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api -->
		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>

		<!-- https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api -->
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>

		<!-- using javamelody-core for monitoring / planned for future version ->
		<dependency>
			<groupId>net.bull.javamelody</groupId>
			<artifactId>javamelody-core</artifactId>
			<version>1.86.0</version>
		</dependency>
		<!- -->
		
		<!-- Plugin for library version checks and updates
		     Source: https://mvnrepository.com/artifact/org.codehaus.mojo/versions-maven-plugin 
		-->
		<dependency>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>versions-maven-plugin</artifactId>
			<version>2.21.0</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<!-- put Lombok on the APT path
							Without this I got lots of compile errors re. missing "log"-variables 
							(obviously "@Slf4j" had not been properly resolved...). 
							See https://stackoverflow.com/questions/79738546/maven-lombok-slf4j-on-jdk-21-cannot-find-symbol-variable-log-even-though 
						-->
						<annotationProcessorPaths>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${lombok.version}</version>
							</path>
						</annotationProcessorPaths>
						<!-- -->
					</configuration>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>3.5.5</version>
				</plugin>

				<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.->
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.apache.cxf</groupId>
										<artifactId>cxf-codegen-plugin</artifactId>
										<versionRange>[1.0,)</versionRange>
										<goals>
											<goal>generate</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore/> <!-` ignored while the execution of this plugin on a Java>v8-JRE always yields:
												Execution generate-sources of goal org.apache.cxf:cxf-codegen-plugin:3.1.5:wsdl2java failed:
												A required class was missing while executing org.apache.cxf:cxf-codegen-plugin:3.1.5:wsdl2java:
												javax/xml/bind/annotation/adapters/HexBinaryAdapter
											->
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
				<!- -->

				<!-- check for valid license headers: -->
				<plugin>
					<groupId>com.mycila</groupId>
					<artifactId>license-maven-plugin</artifactId>
					<version>5.0.0</version>
					<configuration>
						<properties>
							<owner>Michael Moser</owner>
							<email>17732576+mmoser18@users.noreply.github.com</email>
							<years>2020-2026</years>
							<skip>false</skip>
						</properties>
						<licenseSets>
							<licenseSet>
								<header>${project.basedir}/LicenseHeader.txt</header>
								<includes>
									<include>**/src/**/*.java</include>
								</includes>
								<excludes>
									<exclude>**/target/**</exclude>
									<exclude>**/config/**</exclude>
									<exclude>**/data/**</exclude>
									<exclude>**/docs/**</exclude>
									<exclude>**/frontend/**</exclude>
									<exclude>**/garage/**</exclude> <!-- leave my private stuff alone! -->
									<exclude>**/vaadin/**</exclude>
								</excludes>
							</licenseSet>
						</licenseSets>
						<mapping>
							<java>JAVADOC_STYLE</java>
						</mapping>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>check</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<configuration>
						<processDependencyManagement>false</processDependencyManagement>
						<processPluginDependenciesInPluginManagement>false</processPluginDependenciesInPluginManagement>
						<!-- Ignore unstable versions globally: -->
						<ignoredVersions>
							<ignoredVersion>.*-M.*</ignoredVersion>
							<ignoredVersion>.*-alpha.*</ignoredVersion>
							<ignoredVersion>.*-Alpha.*</ignoredVersion>
							<ignoredVersion>.*-beta.*</ignoredVersion>
							<ignoredVersion>.*-Beta.*</ignoredVersion>
							<ignoredVersion>.*-b\d*</ignoredVersion> <!---b06 -->
							<ignoredVersion>.*-rc.*</ignoredVersion>
							<ignoredVersion>.*-RC.*</ignoredVersion>
							<ignoredVersion>.*\.Dev.*</ignoredVersion>
							<ignoredVersion>.*-SNAPSHOT</ignoredVersion>
						</ignoredVersions>
						<!-- Example: Exclude specific project dependencies ->
						<dependencyExcludes>
							<dependencyExclude>org.slf4j:slf4j-simple</dependencyExclude>
							<dependencyExclude>dom4j:dom4j</dependencyExclude>
						</dependencyExcludes>
						<!- -->
						<!-- Example: Exclude plugin transitive dependencies ->
						<pluginDependencyExcludes>
							<pluginDependencyExclude>
								org.codehaus.plexus:plexus-utils</pluginDependencyExclude>
						</pluginDependencyExcludes>
						<!- -->
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
		
		<defaultGoal>spring-boot:run</defaultGoal>
		
		<plugins>
			<plugin>
				<groupId>com.mycila</groupId>
				<artifactId>license-maven-plugin</artifactId>
			</plugin>
			<!-- -->
			
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<!-- Clean build and startup time for Vaadin apps sometimes may exceed the default Spring Boot's 30sec timeout. -->
					<wait>500</wait>
					<maxAttempts>240</maxAttempts>
					<!-- the following is for the co-existence of Lombok and AspectJ: -> 
					<agent>
						<agentElement>
							${user.repo}org/springframework/spring-instrument/${spring.version}/spring-instrument-${spring.version}.jar
						</agentElement>
						<agentElement>
							${user.repo}org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
						</agentElement>
					</agent>
					<systemPropertyVariables>
						<aj.weaving.loadersToSkip>
							org.springframework.context.support.ContextTypeMatchClassLoader$ContextOverridingClassLoader,
							org.springframework.data.jpa.repository.config.InspectionClassLoader
						</aj.weaving.loadersToSkip>
					</systemPropertyVariables>
					<!- -->
				</configuration>
			</plugin>

			<!-- Takes care of synchronizing java dependencies and imports in package.json 
				and main.js files. It also creates webpack.config.js if not exists yet. -->
			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-frontend</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin> <!-- according to Vaadin docs required for Java v9+ - but it doesn't tell which version :-( -->
				<artifactId>maven-failsafe-plugin</artifactId>
				<dependencies>
					<!-- https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl -->
					<dependency>
						<groupId>com.sun.xml.bind</groupId>
						<artifactId>jaxb-impl</artifactId>
						<version>${jaxb.version}</version>
					</dependency>
				</dependencies>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<excludes> <!-- these should be provided externally to the .jar: -->
						<exclude>**/application.properties</exclude>
						<exclude>**/logback.xml</exclude>
						<exclude>com/vaadin/flow/components/charts**</exclude>
					</excludes>
					<archive>
						<manifestEntries>
							<!-- to be able to locate application.properties and 
								logback.xml files in the same folder as the .jar: 
							-->
							<Class-Path>.</Class-Path>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<!-- Production mode is activated using -Pproduction -->
			<id>production</id>
			<properties>
				<vaadin.productionMode>true</vaadin.productionMode>
			</properties>

			<dependencies>
				<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>flow-server-production-mode</artifactId>
				</dependency>
			</dependencies>

			<build>
				<plugins>
					<!-- -->
					<plugin>
						<groupId>com.mycila</groupId>
						<artifactId>license-maven-plugin</artifactId>
					</plugin>
					<!-- -->
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<configuration>
							<jvmArguments>-Dvaadin.productionMode</jvmArguments>
						</configuration>
					</plugin>
					<plugin>
						<groupId>com.vaadin</groupId>
						<artifactId>vaadin-maven-plugin</artifactId>
						<version>${vaadin.version}</version>
						<executions>
							<execution>
								<goals>
									<goal>prepare-frontend</goal>
									<goal>build-frontend</goal>
								</goals>
								<phase>compile</phase>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>unit-tests</id> <!-- will only be executed if "-Punit-tests" is passed on the mvn cmd-line -->
			<build>
				<plugins>
					<plugin> <!-- this plugin runs the Unit Tests (Integrations Tests are excluded) -->
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<executions>
							<execution>
								<goals>
									<goal>test</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<excludes>
								<exclude>**/*IT.java</exclude> <!-- Excludes integration tests when unit tests are run. -->
							</excludes>
							<!-- Found here: https://www.robingander.de/blog/2019/aspectj-spring-boot-lombok.html
								See https://github.com/subes/invesdwin-instrument instead, this can load the spring-instrument into the running JVM
								There arose some problems in a real application where the spring instrumentation and aspectjweaver did weave 
								classes in a circular loop. Happily the aspectjweaver has an undocumented system property (-Daj.weaving.loadersToSkip=...) 
								to exclude springs classloaders, to overcome this problem ->
							<argLine>
								-javaagent:${user.home}/.m2/repository/org/springframework/spring-instrument/${spring.version}/spring-instrument-${spring.version}.jar
								-javaagent:${user.home}/.m2/repository/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
								-Daj.weaving.loadersToSkip=org.springframework.context.support.ContextTypeMatchClassLoader$ContextOverridingClassLoader,org.springframework.data.jpa.repository.config.InspectionClassLoader
							</argLine>
							<!- -->
						</configuration>
					</plugin>

					<!-- JaCoCo: Code Coverage (runs as part of unit tests)
					     Note: When using the maven-surefire-plugin or maven-failsafe-plugin you must not use a 
					     forkCount of 0 or set the forkMode to never as this would prevent the execution of the 
					     tests with the javaagent set and no coverage would be recorded. 
					-->
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>0.8.13</version>
						<executions>
							<!-- Prepares the property pointing to the JaCoCo runtime agent which 
								is passed as VM argument when the Maven Surefire plugin is executed. -->
							<execution>
								<id>pre-unit-test</id>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
								<configuration>
									<!-- Sets the name of the property containing the settings for JaCoCo runtime agent. -->
									<propertyName>surefireArgLine</propertyName>
								</configuration>
							</execution>
							<!-- Ensures that the code coverage report for unit tests is created after unit tests have been run. -->
							<execution>
								<id>post-unit-test</id>
								<phase>test</phase>
								<goals>
									<goal>report</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>integration-tests</id>	<!-- will only be executed if "-Pintegration-tests" is passed on the mvn cmd-line -->
			<build>
				<plugins>
					<!-- To run the integration test the webserver must be started before and stopped afterwards. -->
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<executions>
							<execution> <!-- in phase "pre-integration-test" run the plugin's goal "start": -->
								<id>start-spring-boot</id>
								<phase>pre-integration-test</phase>
								<goals>
									<goal>start</goal>
								</goals>
							</execution>
							<execution> <!-- in phase "post-integration-test" run the plugin's goal "stop": -->
								<id>stop-spring-boot</id>
								<phase>post-integration-test</phase>
								<goals>
									<goal>stop</goal>
								</goals>
							</execution>
						</executions>
					</plugin>

					<!-- This plugin runs the integration tests:
					     Note: The name of the test classes needs to end in '...IT' for the test runner to pick it up as an 
					     integration test. Otherwise they will be picked up as unit-test and the test will (most likely) fail 
					-->
					<plugin> <!-- This plugin runs the integration tests (i.e. tests named *IT) after the server is started -->
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<trimStackTrace>false</trimStackTrace>
							<enableAssertions>true</enableAssertions>
							<!--  ->
							<argLine>
								-javaagent:${user.home}/.m2/repository/org/springframework/spring-instrument/${spring.version}/spring-instrument-${spring.version}.jar
								-javaagent:${user.home}/.m2/repository/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
								-Daj.weaving.loadersToSkip=org.springframework.context.support.ContextTypeMatchClassLoader$ContextOverridingClassLoader,org.springframework.data.jpa.repository.config.InspectionClassLoader
							</argLine>
							<!- -->
						</configuration>
					</plugin>

					<!-- what is/was that for? -->
					<plugin>
						<groupId>org.owasp</groupId>
						<artifactId>dependency-check-maven</artifactId>
						<version>12.2.0</version>

						<configuration>
							<formats>
								<format>html</format>
								<format>json</format>
							</formats>
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>check</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					
				</plugins>
			</build>
		</profile>

	</profiles>
</project>